export enum SalesOrderStatus {
  DRAFT = 'DRAFT',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
}

export enum LocationType {
  INTERNAL = 'INTERNAL',
  VENDOR = 'VENDOR',
  CUSTOMER = 'CUSTOMER',
  INVENTORY_LOSS = 'INVENTORY_LOSS',
  PRODUCTION = 'PRODUCTION',
  TRANSIT = 'TRANSIT',
  VIEW = 'VIEW',
  ASSET_ALLOCATION = 'ASSET_ALLOCATION',
}
